## Unsupervised Learning

```{r}
library("tidymodels")
library("tidyverse")
```

## Principal Components Analysis

```{r}
usarrests = as_tibble(USArrests, rownames = "state")
glimpse(usarrests)
skimr::skim(usarrests)
```

```{r}
# scale before applyig PCA
set.seed(1)
pca_recipe = recipe(~ ., data = usarrests) %>% 
    step_scale(all_numeric()) %>% 
    step_pca(all_numeric(), id = "pca") %>% 
    prep()

usarrests %>% 
    column_to_rownames("state") %>% 
    prcomp(scale = TRUE) %>% 
    factoextra::fviz_pca_biplot(title = "Biplot PCA on usarrests")

# loadings
tidy(pca_recipe, type = "coef", id = "pca")

tidy(pca_recipe, type = "coef", id = "pca") %>% 
    pivot_wider(id_cols = "terms"
                , names_from = "component"
                , values_from = "value"
                )

# variance
tidy(pca_recipe, type = "variance", id = "pca")

tidy(pca_recipe, type = "variance", id = "pca") %>% 
    pivot_wider(id_cols = "terms"
                , names_from = "component"
                , names_prefix = "PC_"
                , values_from = "value"
                )
# cumulative varianvce plot
tidy(pca_recipe, type = "variance", id = "pca") %>% 
    filter(terms == "cumulative variance") %>% 
    ggplot(aes(component, value)) +
        geom_point() +
        geom_line() +
        ylim(c(0, 100)) +
        ylab("Cumulative variance")
```


```{r}
# on the direct PCA object
usarrests_pca = usarrests %>% 
    select(-state) %>% 
    prcomp(scale = TRUE)

tidy(usarrests_pca)
augment(usarrests_pca)
```

## Kmeans Clustering

```{r}
set.seed (2)
x = matrix(rnorm (50*2), ncol = 2)
x[1:25 ,1] = x[1:25 ,1] + 3
x[1:25 ,2] = x[1:25 ,2] - 4


x_df = as_tibble(setNames(x, c("V1", "V2")))
x_df
skimr::skim(x_df)
```

```{r}
res_kmeans = kmeans(x_df, centers = 3, nstart = 20)
glance(res_kmeans)
tidy(res_kmeans, )
augment(res_kmeans, data = x_df)
```

## Hierarchical Clustering

```{r}
res_hclust_complete = x_df %>% 
    dist() %>% 
    hclust(method = "complete")

res_hclust_average = x_df %>% 
    dist() %>% 
    hclust(method = "average")

res_hclust_single = x_df %>% 
    dist() %>% 
    hclust(method = "single")

patchwork::wrap_plots(
    factoextra::fviz_dend(res_hclust_complete, main = "complete", k = 2),
    factoextra::fviz_dend(res_hclust_average, main = "average", k = 2),
    factoextra::fviz_dend(res_hclust_single, main = "single", k = 2),
    ncol = 1
    )
```

```{r}
# clustering with scaled features
x_df %>% 
    scale() %>% 
    dist() %>% 
    hclust(method = "complete") %>% 
    factoextra::fviz_dend(k = 2)

# correlation based distance
set.seed(2)
x = matrix(rnorm(30*3), ncol = 3)

x %>% 
    proxy::dist(method = "correlation") %>% 
    hclust(method = "complete") %>% 
    factoextra::fviz_dend()
```

## PCA on the NCI60 Data

```{r}
data(NCI60, package = "ISLR")
nci60 = NCI60$data %>% 
    as_tibble() %>% 
    magrittr::set_colnames(., paste0("V_", 1:ncol(.))) %>% 
    mutate(label = factor(NCI60$labs)) %>% 
    relocate(label)

nci60 %>% 
    count(label, sort = TRUE)

nci60_pca = prcomp(nci60 %>% select(-label), scale = TRUE)
tidy(nci60_pca)
augment(nci60_pca)

pc_first_three = augment(nci60_pca) %>% 
    select(c(.fittedPC1, .fittedPC2, .fittedPC3)) %>% 
    mutate(label = factor(NCI60$labs))

patchwork::wrap_plots(
    pc_first_three %>% 
        ggplot(aes(.fittedPC1, .fittedPC2, color = label)) +
            geom_point(size = 5, alpha = 0.5) +
            scale_color_discrete(guide = FALSE),
    pc_first_three %>% 
        ggplot(aes(.fittedPC1, .fittedPC3, color = label)) +
        geom_point(size = 5, alpha = 0.5)
    )    

summary(nci60_pca)$importance %>% 
    t() %>% 
    as_tibble(.name_repair = "universal") %>% 
    rowid_to_column() %>% 
    select(-Standard.deviation) %>% 
    pivot_longer(cols = -rowid) %>% 
    ggplot(aes(rowid, value)) +
        geom_point() +
        geom_line() +
        facet_wrap(name ~ ., scales = "free") +
        xlab("Principal Component")
```

## Clustering on nci60 dataset

```{r}
nci60_scaled_mat = nci60 %>% 
    select(-label) %>% 
    as.matrix() %>% 
    scale()
rownames(nci60_scaled_mat) = as.character(nci60$label)

# hierarchical clustering of NIC60 data
produce_dend = function(method){
    
    nci60_scaled_mat %>% 
        dist() %>% 
        hclust(method = method) %>% 
        factoextra::fviz_dend()
    
}

patchwork::wrap_plots(
    produce_dend("complete"),
    produce_dend("average"),
    produce_dend("single"),
    ncol = 1
    )

res_hclust_complete = nci60_scaled_mat %>% 
    dist() %>% 
    hclust(method = "complete")

res_hclust_complete %>% 
    factoextra::fviz_dend(k = 4, main = "hclust(complete) on nci60")

tibble(label = nci60$label, 
       cluster_id = cutree(res_hclust_complete, k = 4)
       ) %>% 
    count(label, cluster_id) %>% 
    group_by(cluster_id) %>% 
    mutate(prop = n/sum(n)) %>% 
    slice_max(n = 1, order_by = prop) %>%
    ungroup()

set.seed(2)
res_kmeans_scaled = kmeans(nci60_scaled_mat, centers = 4, nstart = 20)
glance(res_kmeans_scaled)
tidy(res_kmeans_scaled) %>% 
    select(cluster, size, withinss)

cluster_kmeans = res_kmeans_scaled$cluster
cluster_hclust = cutree(res_hclust_complete, k = 4)

tibble(kmeans = factor(cluster_kmeans),
       hclust = factor(cluster_hclust)
       ) %>% 
    conf_mat(kmeans, hclust)

mclust::adjustedRandIndex(cluster_kmeans, cluster_hclust)

# pick first five PC and observe the clusters from hclust
nci60_scaled_mat %>% 
    unname() %>% 
    prcomp() %>% 
    tidy() %>% 
    filter(PC <= 5) %>% 
    pivot_wider(id_cols = row,
                names_from = PC,
                values_from = value,
                names_prefix = "PC_"
                ) %>% 
    select(-row) %>%
    as.matrix() %>% 
    magrittr::set_rownames(nci60$label) %>% 
    dist() %>% 
    hclust() %>% 
    factoextra::fviz_dend(k = 4, main = "hclust on first five PCs")
```

