# Introduction

This book aims to be a complement to the 2nd version [An Introduction to Statistical Learning](https://www.statlearning.com/) book with translations of the labs into using the [tidymodels](https://www.tidymodels.org/) set of packages.

The labs will be mirrored quite closely to stay true to the original material.

## Version Differences {-}

all listed changes will be relative to the 1st version.

- [Naive Bayes](04-classification.qmd#naive-bayes) has been added to chapter 4 on [Classification](04-classification.qmd)
- [Poisson Regression](04-classification.qmd#poisson-regression) has been added to chapter 4 on [Classification](04-classification.qmd)
- "Application to Caravan Insurance Data" section is no longer treated as its own section and is now part of the [K-Nearest Neighbors](04-classification.qmd#k-nearest-neighbors) section
- [Bayesian Additive Regression Trees](08-tree-based-methods.qmd#bayesian-additive-regression-trees) has been added to chapter 8 on [Tree-Based Methods](08-tree-based-methods.qmd)
- chapter on [Unsupervised Learning](12-unsupervised-learning.qmd) has been renumbered to chapter 12 instead of 10
- [Matrix Completion](12-unsupervised-learning.qmd#matrix-completion) has been added to chapter 12 on [Unsupervised Learning](12-unsupervised-learning.qmd)
- chapter on [Deep learning](10-deep-learning.qmd) has been added as chapter 10
- chapter on [Survival Analysis and Censored Data](11-survival-analysis.qmd) as been added as chapter 11
- chapter on [Multiple Testing](13-multiple-testing.qmd) as been added as chapter 13

## Colophon {-}

This book was written in [RStudio](http://www.rstudio.com/ide/) using [**quarto**](https://quarto.org/). The [website](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html) is hosted via [GitHub Pages](https://pages.github.com/), and the complete source is available on [GitHub](https://github.com/EmilHvitfeldt/ISLR-tidymodels-labs).

This version of the book was built with `r R.version.string` and the following packages:

```{r, echo = FALSE, results="asis"}
deps <- desc::desc_get_deps()
pkgs <- sort(deps$package[deps$type == "Imports"])
pkgs <- sessioninfo::package_info(pkgs, dependencies = FALSE)
df <- tibble::tibble(
  package = pkgs$package,
  version = pkgs$ondiskversion,
  source = gsub("@", "\\\\@", pkgs$source)
)
knitr::kable(df, format = "markdown")
```
